# .github/workflows/ci.yml

name: CI
on:
  pull_request:
    types: [closed]

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: PR Closed - Destroy Review App
        run: echo "closingggg"
