# .github/workflows/ci.yml

name: CI
on:
  pull_request:
    types: [labeled]

jobs:
  create-review-app:
    if: ${{ github.event.label.name == "deploy-review-app" }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Deploy Review App
        run: echo "Deployyyy"

  destroy-review-app:
    if: ${{ github.event.label.name == "destroy-review-app" }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Destroy Review App
        run: echo "Destroyyy"
