# .github/workflows/ci.yml

name: CI
on:
  pull_request:
    types: [labeled]

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: echo labeled
        run: echo $ENV
