# .github/workflows/ci.yml

name: CI
on:
  pull_request:
    types: [unlabeled]

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: echo unlabeled
        run: echo ${{ github.event.label.name }}
